Repository davbrican/InnoBuddy, pull requests merged in 2022-01, with the labels that each got.

#55 feat: Pruebas del comando /socialmedias
  src/commands/mensajes.json
  src/tests/test_commands.py
Labels: priority: low, testing

#65 Test/issue 64
  src/tests/test_commands.py
Labels: priority: medium, testing

#69 feat: Añadido nuevos comandos
  src/commands/mensajes.json
  src/handlers.py
Labels: new feature, priority: medium

#81 fix: Ejecución pruebas
  src/tests/test_commands.py
Labels: bug, priority: high

#77 feat: Pruebas comando fechas
  src/tests/test_commands.py
Labels: priority: medium, testing

#75 feat: Pruebas comando localización
  src/tests/test_commands.py
Labels: priority: medium, testing

#109 feat: Añadido el comando /recordatorios
  src/commands/mensajes.json
  src/handlers.py
Labels: new feature, priority: medium

#104 Env/issue 89
  docker/Dockerfile
  docker/docker-compose.yml
Labels: priority: high, environment

#129 test: Añadido test para el comando /eventos hoy
  src/tests/test_commands.py
Labels: priority: medium, testing

#133 feat: Prueba localización service
  src/tests/test_localizaciones_service.py
Labels: priority: medium, testing

#139 feat: Añadido tests del comando /admin
  src/tests/test_commands.py
Labels: priority: medium, testing
